STANDARD_CATEGORY = {
    "pedestrian": "Pedestrian Infrastructure",
    "bump outs": "Pedestrian Infrastructure",
    "bicycle": "Bicycle Infrastructure",
    "bike": "Bicycle Infrastructure",
    "neighborhood greenway": "Bicycle Infrastructure",
    "light": "Lighting",
    "street resurfacing": "Street Resurfacing",
    "street speed hump replacement": "Street Resurfacing",
    "curb & gutter": "Street Resurfacing",
    "alley": "Alleys",
    "miscellaneous cdot projects": "Misc. CDOT",
    "mural": "Beautification",
    "public art": "Beautification",
    "tree planting": "Beautification",
    "turn arrow": "Street Redesign",
    "street speed hump menu": "Street Redesign",
    "pavement markings": "Street Redesign",
    "traffic circle": "Street Redesign",
    "cul-de-sac": "Street Redesign",
    "diagnol parking": "Street Redesign",
    "sidewalk": "Sidewalk Repair",
    "pod camera": "Police Cameras",
    "park": "Parks",
    "playground": "Parks",
    "garden": "Parks",
    "viaduct": "Viaducts",
}
